backend:
  name: proxy
  proxy_url: http://localhost:8081/api/v1
  branch: master # optional, defaults to master
  commit_messages:
    create: "Create {{collection}} '{{slug}}'"
    update: "Update {{collection}} '{{slug}}'"
    delete: "Delete {{collection}} '{{slug}}'"
    uploadMedia: "[skip ci] Upload '{{path}}'"
    deleteMedia: "[skip ci] Delete '{{path}}'"

site_url: "https://nitratine.net"
display_url: "https://nitratine.net"

media_folder_relative: true
media_folder: static/assets
public_folder: /assets

collections:
  - name: "post"
    label: "Blog"
    folder: "src/pages/blog/post"
    create: true
    slug: "index"
    path: "{{title}}/{{slug}}"
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Hidden", name: "hidden", widget: boolean, default: false }
      - { label: "Disable Table Of Contents", name: "disableToc", widget: boolean, default: false }
      - {
          label: "GitHub Repository",
          name: "githubRepository",
          widget: string,
          default: null,
          required: false,
        }
      - { label: "Featured Image", name: "image", widget: image }
      - { label: "Description", name: "description", widget: "text", default: "" }
      - {
          label: "YouTube Video",
          name: "youtubeVideoId",
          widget: "string",
          default: null,
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page" }
          - { label: Image, name: image, widget: image }
          - { label: Lead Text, name: leadText, widget: string }
          - {
              label: Buttons,
              name: buttons,
              widget: list,
              fields:
                [
                  { label: Text, name: text, widget: string },
                  { label: Link, name: link, widget: string },
                  {
                    label: Type,
                    name: type,
                    widget: select,
                    required: true,
                    multiple: false,
                    default: ["primary"],
                    options:
                      [
                        { label: "Primary", value: "primary" },
                        { label: "Secondary", value: "secondary" },
                      ],
                  },
                ],
            }
          - {
              label: "Featured Posts",
              name: featuredPosts,
              widget: list,
              fields:
                [
                  {
                    label: "Type",
                    name: "type",
                    widget: "select",
                    default: "post",
                    options:
                      [
                        { label: "Post", value: "post" },
                        { label: "Post Image", value: "postImage" },
                        { label: "Raw", value: "raw" },
                        { label: "Raw Body", value: "rawBody" },
                      ],
                    required: true,
                  },
                  { label: "Post", name: "post", widget: "string" },
                  {
                    label: "Raw HTML",
                    name: "rawHtml",
                    widget: "code",
                    default_language: html,
                    output_code_only: true,
                    required: false,
                  },
                ],
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Email", name: "email", widget: "string" }
          - {
              label: Experience,
              name: experience,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Image, name: img, widget: image },
                ],
            }
      - file: "src/pages/portfolio/index.md"
        label: "Portfolio"
        name: "portfolio"
        media_folder: ""
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "portfolio-page",
            }
          - { label: Body, name: body, widget: markdown }

  - name: "config"
    label: "Config"
    files:
      - file: "src/config/sidebar.json"
        label: "SideBar"
        name: "sidebar"
        fields:
          - { label: "Config Key", name: "configKey", widget: "hidden", default: "sidebar" }
          - { label: "About", name: "about", widget: "markdown" }
          - {
              label: Category Prefixes,
              name: categoryPrefixes,
              widget: list,
              fields:
                [
                  { label: Category, name: category, widget: string },
                  { label: Prefix, name: prefix, widget: string },
                ],
            }
          - {
              label: Featured Sites,
              name: featuredSites,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Image, name: imageSrc, widget: image },
                  { label: Link, name: href, widget: string },
                ],
            }
          - {
              label: YouTube,
              name: youtube,
              widget: object,
              fields:
                [
                  {
                    label: "Channel Id (Requires Restart)",
                    name: "channelId",
                    widget: "string",
                    default: "",
                  },
                  {
                    label: "Recent Video Amount (Requires Restart)",
                    name: "recentViewAmount",
                    widget: "number",
                    default: 6,
                  },
                ],
            }
      - file: "src/config/navigation.json"
        label: "Navigation"
        name: "navigation"
        fields:
          - { label: "Config Key", name: "configKey", widget: "hidden", default: "navigation" }
          - {
              label: Links,
              name: links,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Link, name: path, widget: string },
                ],
            }
